# Install modules from the forge with dependencies
mod 'puppetlabs/stdlib'
mod 'puppetlabs/ntp'
mod 'puppetlabs/apache'
mod 'puppetlabs/concat'
mod 'puppetlabs/puppetserver_gem'

mod 'herculesteam/augeasproviders_core'
mod 'camptocamp/augeas'
mod 'puppet/puppetserver'

mod 'puppetlabs/firewall'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/inifile'

mod 'puppet/puppetboard'
mod "puppetlabs/vcsrepo"
mod "puppet/python"
mod "puppet/epel"

mod 'puppet/jenkins'
mod 'puppet/nginx'

mod 'puppetlabs/java'
mod 'puppet/archive'
mod 'puppet/profile_nginx', :git => 'git@github.rackspace.com:TEASandbox/puppet-profile_nginx.git'
